CMS/Controllers/MenuQuanTriController.cs
using Application.Interfaces;
using CMS.Models;
using Domain.Entities;
using Domain.Models;
using Domain.Querys;
using Domain.Querys.Base;
using Microsoft.AspNetCore.Mvc;

namespace CMS.Controllers
{
    public class MenuQuanTriController : BaseController
    {
        private readonly IMenuQuanTriService _MenuQuanTriService;
        public MenuQuanTriController(INguoiDungService nguoiDungService,IMenuQuanTriService MenuQuanTriService) : base(nguoiDungService)
        {
            _MenuQuanTriService = MenuQuanTriService;
        }
        public IActionResult Index()
        {
            return View();
        }


        public IActionResult GetMenuItems()
        {
            return Ok(_MenuQuanTriService.GetTreeMenuTreeView());
        }
        public IActionResult AddSubItem(int Id)
        {
            MenuQuanTri_Entity itemMenu = new MenuQuanTri_Entity();
            if (Id != 0)
            {
                var itemMenuParrent = _MenuQuanTriService.GetEntity(Id);
                itemMenu.MenuCha = itemMenuParrent;
            }
            return View("Edit", itemMenu);
        }
        public IActionResult GetMenuIdByVaiTroIdAndNguoiDungId(int idNguoiDung, string IdVaiTroString)
        {
            List<int> result = _MenuQuanTriService.GetMenuIdByVaiTroIdAndNguoiDungId(idNguoiDung,IdVaiTroString);
            return Ok(result);
        }

        public IActionResult Edit(int Id)
        {
            MenuQuanTri_Entity itemEdit = new MenuQuanTri_Entity();
            if (Id != 0)
                itemEdit = _MenuQuanTriService.GetEntity(Id);
            return View(itemEdit);
        }
        public IActionResult View(int Id)
        {
            MenuQuanTri_Entity itemEdit = _MenuQuanTriService.GetEntity(Id);
            return PartialView(itemEdit);
        }

        public IActionResult Update(MenuQuanTri oItem)
        {
            try
            {
                oItem.CurrentUserId = GetCurrentUser().Id;
                var responeActionResult = _MenuQuanTriService.Update(oItem);
                return Ok(responeActionResult);
            }
            catch (Exception ex)
            {
                //Log.Error(ex, "Lỗi khi sửa");
                return StatusCode(500, "Đã có lỗi xảy ra. Vui lòng thử lại sau.");
            }


        }
        public IActionResult Approved(int Id)
        {
            try
            {
                var responeActionResult =  _MenuQuanTriService.ApprovedItem(Id);
                return Ok(responeActionResult);
            }
            catch (Exception ex)
            {
                //Log.Error("Lỗi ở /TaiLieuThucTap/Approved", ex);
                return StatusCode(500, "Đã có lỗi xảy ra. Vui lòng thử lại sau.");
            }
        }

        public IActionResult Disapproval(int Id)
        {
            try
            {
                var responeActionResult = _MenuQuanTriService.DisapprovedItem(Id);
                return Ok(responeActionResult);
            }
            catch (Exception ex)
            {
                //Log.Error("Lỗi ở /TaiLieuThucTap/Disapproval", ex);
                return StatusCode(500, "Đã có lỗi xảy ra. Vui lòng thử lại sau.");
            }


        }
        public IActionResult Delete(int Id)
        {
            try
            {
                var responeActionResult = _MenuQuanTriService.Delete(Id);
                return Ok(responeActionResult);
            }
            catch (Exception ex)
            {
                //Log.Error("Lỗi ở /TaiLieuThucTap/Delete", ex);
                return StatusCode(500, "Đã có lỗi xảy ra. Vui lòng thử lại sau.");
            }


        }
        public IActionResult Insert(MenuQuanTri oItem)
        {
            try
            {
                oItem.CurrentUserId = GetCurrentUser().Id;
                var responeActionResult = _MenuQuanTriService.Insert(oItem);
                return Ok(responeActionResult);

            }
            catch (Exception ex)
            {
                //Log.Error(ex, "Lỗi khi sửa");
                return StatusCode(500, "Đã có lỗi xảy ra. Vui lòng thử lại sau.");
            }


        }

        public IActionResult GetPaged(MenuQuanTriQuery c_query)
        {

            try
            {
                var responeActionResult = _MenuQuanTriService.GetPaged(c_query);
                return Ok(responeActionResult);
            }
            catch (Exception ex)
            {
                //Log.Error(ex, "Lỗi khi lấy danh sách");
                return StatusCode(500, "Đã có lỗi xảy ra. Vui lòng thử lại sau.");
            }
        }
    }
}

CMS/Views/MenuQuanTri/Edit.cshtml
@model Domain.Entities.MenuQuanTri_Entity

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var oMenuCha = Model.MenuCha;
    string oMenuChaJson = oMenuCha != null ? Newtonsoft.Json.JsonConvert.SerializeObject(oMenuCha) : "{}";
}

<div class="container-fluid">
    <div class="page-title">
        <div class="row">
            <div class="col-6">
                <h4>
                    @if (Model.Id > 0)
                    {
                        <text>Sửa menu menu quản trị</text>
                    }
                    else
                    {
                        <text>Thêm mới menu quản trị</text>
                    }
                </h4>
            </div>
            <div class="col-6">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="index.html">
                            <svg class="stroke-icon">
                                <use href="../assets/svg/icon-sprite.svg#stroke-home"></use>
                            </svg>
                        </a>
                    </li>
                    <li class="breadcrumb-item"> Chức năng hệ thống</li>
                    <li class="breadcrumb-item">Menu quản trị</li>
                    <li class="breadcrumb-item active">
                        @if (Model.Id > 0)
                        {
                            <text>Sửa menu</text>
                        }
                        else
                        {
                            <text>Thêm mới</text>
                        }
                    </li>
                </ol>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <form asp-action="@(Model.Id == 0 ? "Insert" : "Update")" asp-controller="MenuQuanTri" method="post" class="card needs-validation">
                <div class="card-header">
                    <h4>Sửa bản ghi</h4>
                </div>
                <div class="card-body custom-input">
                    <div class="row">
                        @if (Model.Id > 0)
                        {
                            <input asp-for="Id" type="hidden" />
                        }
                        <div class="col-md-8">
                            <div class="mb-3">
                                <label asp-for="TenMenu" class="form-label">Tên menu</label>
                                <input asp-for="TenMenu" class="form-control " placeholder="Tên menu" required />
                                <span asp-validation-for="TenMenu" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="mb-3">
                                <label asp-for="Icon" class="form-label">Mã icon fontawesome</label>
                                <input asp-for="Icon" class="form-control " placeholder="Mã icon" required />
                                <span asp-validation-for="Icon" class="text-danger"></span>
                            </div>
                        </div>


                        <div class="col-md-12">
                            <div class="mb-3">
                                <label asp-for="MenuChaId" class="form-label ">Menu cha ( menu trực thuộc)</label>
                                <select asp-for="MenuChaId" class="form-control " placeholder="Menu cha"></select>
                                <span asp-validation-for="MenuChaId" class="text-danger"></span>

                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="mb-3">
                                <label asp-for="ViTri" class="form-label">Vị trí đứng</label>
                                <input asp-for="ViTri" type="number" class="form-control" placeholder="Số thứ tự" required />
                                <span asp-validation-for="ViTri" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="mb-3">
                                <label asp-for="LienKet" class="form-label ">Đường dẫn</label>
                                <input asp-for="LienKet" class="form-control " placeholder="Đường dẫn" />
                                <span asp-validation-for="LienKet" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="mb-3">
                                <input type="checkbox" asp-for="Category" class="form-check-label " placeholder="Đường dẫn" />
                                <label asp-for="Category" class="form-check-label">Menu này là danh mục</label>
                            </div>
                        </div>


                        <div class="col-md-12 text-end">
                            <button id="save" type="button">Lưu</button>
                        </div>
                    </div>


                </div>


            </form>
        </div>
    </div>

</div>

<script>
    $(document).ready(function () {
        var oMenuCha = @Html.Raw(oMenuChaJson);
        var initialSelection = oMenuCha ? [{
            text: oMenuCha.TenMenu,
            id: oMenuCha.Id
        }] : [];
        $("#MenuChaId").registerSelect({
            url: '/MenuQuanTri/GetPaged',
            placeholder: "Chọn menu cha",
            queryData: {

            },
            prepareDataRequest: function (params) {
                var parameter = {
                    Keyword: params.term,
                    SearchIn: ["TenMenu"],
                }
                return parameter;
            },

            initialSelection: initialSelection,
            dataProcess: function (data) {
                return {
                    results: data.data.map(function (item) {
                        return {
                            id: item.Id,
                            text: item.TenMenu
                        };
                    })
                };
            },
        });
        $('#save').registerButton({
            type: 'primary',
            icon: "fa fa-plus",
            clickHandler: function () {
                return new Promise(function (resolve) {
                    var form = $("form.needs-validation")[0];
                    if (!form.checkValidity()) {
                        resolve();//Đặt cờ thành công
                        event.preventDefault();
                        event.stopPropagation();
                    } else {
                        event.preventDefault();
                        event.stopPropagation();
                        var data = new FormData(form);
                        var xhr = new XMLHttpRequest();
                        xhr.open(form.method, form.action, true);
                        xhr.onload = function () {
                            resolve();//Đặt cờ thành công
                            if (xhr.status === 200) {
                                console.log(xhr)
                                showNotification("success", "Thao tác thành công!");
                                ChuyenHuong("external", "/MenuQuanTri/Index", "same_tab");
                            } else {

                                showNotification("warning", "Thao tác thất bại!")
                            }
                        };
                        xhr.send(data);

                    };
                    form.classList.add('was-validated');


                });
            }
        });
    });

</script>

CMS/Views/MenuQuanTri/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<div class="container-fluid">
    <div class="page-title">
        <div class="row">
            <div class="col-6">
                <h4>Danh sách menu quản trị</h4>
            </div>
            <div class="col-6">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="index.html">
                            <svg class="stroke-icon">
                                <use href="../assets/svg/icon-sprite.svg#stroke-home"></use>
                            </svg>
                        </a>
                    </li>
                    <li class="breadcrumb-item"> Chức năng hệ thống</li>
                    <li class="breadcrumb-item active">Menu quản trị</li>
                </ol>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-6">
                            <h4>Danh sách menu</h4>
                            <p class="f-m-light mt-1">
                                Quản trị danh sách menu động
                            </p>
                        </div>
                        <div class="col-md-6 text-end">
                            <button id="myButton" type="button" data-permission="002002001">Thêm mới</button>
                        </div>
                    </div>



                </div>
                <div class="card-body">
                    <div id="container" class="tree-container"></div>
                </div>
            </div>
        </div>

    </div>
</div>

<script>


    $(document).ready(function () {


        var treeMenu = $("#container").registerTreeView({
            selectMode: '',
            values: [],
            disables: [],
            beforeLoad: null,
            loaded: null,
            url: "/MenuQuanTri/GetMenuItems",
            editCallback: function (ItemId) {
                ChuyenHuong("external", "/MenuQuanTri/Edit/" + ItemId)
            },
            approvedCallback: function (ItemId) {
                $.ajax({
                    url: '/MenuQuanTri/Approved/' + ItemId,
                    method: 'GET',
                    dataType: 'json',
                    success: function (data) {
                        ChuyenHuong("reload")
                    },
                    error: function (xhr, status, error) {
                        showNotification("danger", 'Đã có lỗi xảy ra:', error);
                    }
                });

            },
            peddingCallback: function (ItemId) {
                $.ajax({
                    url: '/MenuQuanTri/Disapproval/' + ItemId,
                    method: 'GET',
                    dataType: 'json',
                    success: function (data) {
                        ChuyenHuong("reload")
                    },
                    error: function (xhr, status, error) {
                        showNotification("danger", 'Đã có lỗi xảy ra:', error);
                    }
                });
            },
            addsubCallback: function (ItemId) {
                ChuyenHuong("external", "/MenuQuanTri/AddSubItem/" + ItemId)
            },
            deleteCallback: function (ItemId) {
                $.ajax({
                    url: '/MenuQuanTri/Delete/' + ItemId,
                    method: 'GET',
                    dataType: 'json',
                    success: function (data) {
                        ChuyenHuong("reload")
                    },
                    error: function (xhr, status, error) {
                        console.log()
                        showNotification("danger", 'Đã có lỗi xảy ra:' + xhr?.responseJSON?.ex_message);
                    }
                });
            },
            onChange: function () {
                // console.log(this.values);
                // console.log(this.selectedNodes);
                // console.log(this.CurrentSelected);
            },
            method: 'GET',
            closeDepth: 3
        });




        $('#myButton').registerButton({
            type: 'primary',
            icon: "fa fa-plus",
            clickHandler: function () {
                return new Promise(function (resolve) {
                    ChuyenHuong("external", "/MenuQuanTri/Edit")
                    resolve();//cờ xác định kết thúc
                });
            }
        });



    })
</script>

CMS/Views/MenuQuanTri/View.cshtml
@model Domain.Models.MenuQuanTri


<div class="table-responsive invoice-table custom-scrollbar" id="table">
    <table class="table table-bordered table-striped">
        <tbody>
            <tr>
                <td class="item">
                    <h6 class="p-2 mb-0">Trường giá trị</h6>
                </td>
                <td class="Hours">
                    <h6 class="p-2 mb-0">Nội dung</h6>
                </td>

            </tr>
            <tr>
                <td>
                    <label>Id</label>
                </td>
                <td>
                    <p class="itemtext">@Model.Id</p>
                </td>

            </tr>
            
            @if (!string.IsNullOrEmpty(Model.CreatedByText))
            {
                <tr>
                    <td>
                        <label>Người tạo</label>
                    </td>
                    <td>
                        <p class="itemtext">@Model.CreatedByText</p>
                    </td>

                </tr>
            }
            @if (!string.IsNullOrEmpty(Model.LastModifiedByText))
            {
                <tr>
                    <td>
                        <label>Người sửa cuối</label>
                    </td>
                    <td>
                        <p class="itemtext">@Model.LastModifiedByText</p>
                    </td>

                </tr>
            }

           

        </tbody>
    </table>
</div>