CMS/Controllers/VaiTroController.cs
using Application.Interfaces;
using Application.Services;
using Domain.Entities;
using Domain.Models;
using Domain.Querys;
using Domain.Querys.Base;
using Microsoft.AspNetCore.Mvc;

namespace CMS.Controllers
{
    public class VaiTroController : BaseController
    {
        private readonly IVaiTroService _VaiTroService;
        private readonly IMenuQuanTriService _MenuQuanTriService;
        private readonly IQuyenSuDungService _QuyenSuDungService;
        public VaiTroController(INguoiDungService nguoiDungService,IVaiTroService VaiTroService,IMenuQuanTriService menuQuanTriService, IQuyenSuDungService quyenSuDungService) : base(nguoiDungService)
        {
            _VaiTroService = VaiTroService;
            _MenuQuanTriService = menuQuanTriService;
            _QuyenSuDungService = quyenSuDungService;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult GetVaiTroItems()
        {
            return Ok(_VaiTroService.GetTreeVaiTroTreeView());
        }
        public IActionResult PhanQuyen(int Id)
        {

            VaiTro_Entity oVaiTro = new VaiTro_Entity();
            if (Id != 0)
            {
                oVaiTro = _VaiTroService.GetEntity(Id);
                if (oVaiTro == null) { oVaiTro = new VaiTro_Entity(); }
            }
            var allMenuIds = _MenuQuanTriService.GetAllMenuQuanTriIds();
            ViewBag.AllMenuIds = allMenuIds;
            var allMenuChaQuyen = _QuyenSuDungService.GetAllQuyenCha();
            ViewBag.AllQuyenCha = allMenuChaQuyen;
            return PartialView(oVaiTro);
        }

        public IActionResult GetVaiTroMenuByVaiTroId(int Id)
        {
            var responeActionResult = _VaiTroService.GetVaiTroMenuByVaiTroId(Id);
            return Ok(responeActionResult);
        }
        public IActionResult GetVaiTroQuyenByVaiTroId(int Id)
        {
            var responeActionResult = _VaiTroService.GetVaiTroQuyenByVaiTroId(Id);
            return Ok(responeActionResult);
        }


        [HttpPost]
        public IActionResult SavePhanQuyen([FromBody] PhanQuyenRequest request)
        {
            request.NguoiDungId = GetCurrentUser().Id;
            var responeActionResult = _VaiTroService.SavePhanQuyen(request);
            return Ok(responeActionResult);
        }





        public IActionResult Edit(int Id)
        {
            VaiTro_Entity itemEdit = new VaiTro_Entity();
            if (Id != 0)
                itemEdit = _VaiTroService.GetEntity(Id);
            return View(itemEdit);
        }
        public IActionResult View(int Id)
        {
            VaiTro itemEdit = _VaiTroService.GetEntity(Id);
            return PartialView(itemEdit);
        }

        public IActionResult Update(VaiTro oItem)
        {
            try
            {
                var responeActionResult = _VaiTroService.Update(oItem);
                return Ok(responeActionResult);
            }
            catch (Exception ex)
            {
                //Log.Error(ex, "Lỗi khi sửa");
                return StatusCode(500, "Đã có lỗi xảy ra. Vui lòng thử lại sau.");
            }


        }
        public IActionResult Approved(int ID)
        {
            try
            {
                var responeActionResult =  _VaiTroService.ApprovedItem(ID);
                return Ok(responeActionResult);
            }
            catch (Exception ex)
            {
                //Log.Error("Lỗi ở /TaiLieuThucTap/Approved", ex);
                return StatusCode(500, "Đã có lỗi xảy ra. Vui lòng thử lại sau.");
            }
        }

        public IActionResult Disapproval(int ID)
        {
            try
            {
                var responeActionResult = _VaiTroService.DisapprovedItem(ID);
                return Ok(responeActionResult);
            }
            catch (Exception ex)
            {
                //Log.Error("Lỗi ở /TaiLieuThucTap/Disapproval", ex);
                return StatusCode(500, "Đã có lỗi xảy ra. Vui lòng thử lại sau.");
            }


        }
        public IActionResult Delete(int Id)
        {
            try
            {
                var responeActionResult = _VaiTroService.Delete(Id);
                return Ok(responeActionResult);
            }
            catch (Exception ex)
            {
                //Log.Error("Lỗi ở /TaiLieuThucTap/Delete", ex);
                return StatusCode(500, "Đã có lỗi xảy ra. Vui lòng thử lại sau.");
            }


        }
        public IActionResult Insert(VaiTro oItem)
        {
            try
            {
                var responeActionResult = _VaiTroService.Insert(oItem);
                return Ok(responeActionResult);

            }
            catch (Exception ex)
            {
                //Log.Error(ex, "Lỗi khi sửa");
                return StatusCode(500, "Đã có lỗi xảy ra. Vui lòng thử lại sau.");
            }


        }

        public IActionResult GetPaged(VaiTroQuery c_query)
        {

            try
            {
                var responeActionResult = _VaiTroService.GetPaged(c_query);
                return Ok(responeActionResult);
            }
            catch (Exception ex)
            {
                //Log.Error(ex, "Lỗi khi lấy danh sách");
                return StatusCode(500, "Đã có lỗi xảy ra. Vui lòng thử lại sau.");
            }
        }
    }
}

CMS/Views/VaiTro/Edit.cshtml
@model Domain.Entities.VaiTro_Entity

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";

}
<div class="container-fluid">
    <div class="page-title">
        <div class="row">
            <div class="col-6">
                <h4>
                    @if (Model.Id > 0)
                    {
                        <text>Sửa vai trò</text>
                    }
                    else
                    {
                        <text>Thêm vai trò mới</text>
                    }
                </h4>
            </div>
            <div class="col-6">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="index.html">
                            <svg class="stroke-icon">
                                <use href="../assets/svg/icon-sprite.svg#stroke-home"></use>
                            </svg>
                        </a>
                    </li>
                    <li class="breadcrumb-item"> Chức năng hệ thống</li>
                    <li class="breadcrumb-item">Vai trò</li>
                    <li class="breadcrumb-item active">
                        @if (Model.Id > 0)
                        {
                            <text>Sửa</text>
                        }
                        else
                        {
                            <text>Thêm mới</text>
                        }
                    </li>
                </ol>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <form asp-action="@(Model.Id == 0 ? "Insert" : "Update")" asp-controller="VaiTro" method="post" class="card needs-validation">
                <div class="card-header">
                    <h4>Thông tin bản ghi</h4>
                </div>
                <div class="card-body custom-input">
                    <div class="row">
                        @if (Model.Id > 0)
                        {
                            <input asp-for="Id" type="hidden" />
                        }
                        <div class="col-md-6">
                            <div class="mb-3">
                                <label asp-for="TenVaiTro" class="form-label">Tên vai trò</label>
                                <input asp-for="TenVaiTro" class="form-control " placeholder="Tên vai trò" required />
                                <span asp-validation-for="TenVaiTro" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="mb-3">
                                <label asp-for="MoTa" class="form-label">Mô tả</label>
                                <input asp-for="MoTa" class="form-control " placeholder="Mô tả" required />
                                <span asp-validation-for="MoTa" class="text-danger"></span>
                            </div>
                        </div>



                        <div class="col-md-12 text-end">
                            <button id="save" type="button">Lưu</button>
                        </div>
                    </div>


                </div>


            </form>
        </div>
    </div>

</div>
<script>
    function convertToSlug(text) {
        return text.toLowerCase().replace(/ /g, '').normalize('NFD').replace(/[\u0300-\u036f]/g, "");
    }
    $(document).ready(function () {
        $('#save').registerButton({
            type: 'primary',
            icon: "fa fa-plus",
            clickHandler: function () {
                return new Promise(function (resolve) {
                    var form = $("form.needs-validation")[0];
                    if (!form.checkValidity()) {
                        resolve();//Đặt cờ thành công
                        event.preventDefault();
                        event.stopPropagation();
                    } else {
                        event.preventDefault();
                        event.stopPropagation();
                        var data = new FormData(form);
                        var xhr = new XMLHttpRequest();
                        xhr.open(form.method, form.action, true);
                        xhr.onload = function () {
                            resolve();//Đặt cờ thành công
                            if (xhr.status === 200) {
                                console.log(xhr)
                                showNotification("success", "Thao tác thành công!");
                                ChuyenHuong("back");
                            } else {

                                showNotification("warning", "Thao tác thất bại!")
                            }
                        };
                        xhr.send(data);

                    };
                    form.classList.add('was-validated');


                });
            }
        });
    });

</script>

CMS/Views/VaiTro/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">
    <div class="page-title">
        <div class="row">
            <div class="col-6">
                <h4>Danh sách Vai trò</h4>
            </div>
            <div class="col-6">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="index.html">
                            <svg class="stroke-icon">
                                <use href="/svg/icon-sprite.svg#stroke-home"></use>
                            </svg>
                        </a>
                    </li>
                    <li class="breadcrumb-item">Chức năng hệ thống</li>
                    <li class="breadcrumb-item active">Vai trò</li>
                </ol>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row">

        <!-- Server-side processing Starts-->
        <div class="col-sm-12">

            <div class="card">
                <div class="card-header pb-0 card-no-border">
                    <div class="row">
                        <div class="col-md-8">
                            <div class="row">
                                <div class="col-md-6 d-flex" data-permission="000003006">
                                    <input type="text" class="form-control flex-grow-1 me-2" id="search-input" placeholder="Nhập vào từ khóa ..." autocomplete="none">
                                    <button class="btn btn-primary" id="search-btn">Tìm kiếm</button>
                                </div>

                            </div>
                        </div>
                        <div class="col-md-4 text-end">
                            <button id="myButton" type="button" data-permission="000003001"> Thêm mới</button>
                            <button id="exportExcel" type="button" data-permission="000003005">Xuất excel</button>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="table-responsive custom-scrollbar">
                        <table class="display" id="data-source-4" style="width:100%">
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

<script>
    function xemVaiTro(Id) {
        openModalWithApi("/VaiTro/View/" + Id, "lg");
    };
    function phanQuyen(Id) {
        openModalWithApi("/VaiTro/phanquyen/" + Id, "lg");
    };
    function suaVaiTro(Id) {
        ChuyenHuong("external", "/VaiTro/Edit/" + Id);
    };
    function duyetVaiTro(Id) {
        toggleButtonContainerLoading(Id);
        $.ajax({
            url: '/VaiTro/Approved/' + Id,
            method: 'GET',
            dataType: 'json',
            success: function (data) {
                showNotification("success", "Duyệt thành công");
                toggleButtonContainerLoading(Id);
                $('#search-btn').click();
            },
            error: function (xhr, status, error) {
                showNotification("danger", 'Đã có lỗi xảy ra:', error);
                toggleButtonContainerLoading(Id);
            }
        });
    };
    function huyDuyetVaiTro(Id) {
        toggleButtonContainerLoading(Id);
        $.ajax({
            url: '/VaiTro/Disapproval/' + Id,
            method: 'GET',
            dataType: 'json',
            success: function (data) {
                toggleButtonContainerLoading(Id);
                showNotification("success", "Hủy duyệt thành công")

                $('#search-btn').click();
            },
            error: function (xhr, status, error) {
                toggleButtonContainerLoading(Id);
                showNotification("danger", 'Đã có lỗi xảy ra:', error);
            }
        });
    };
    function xoaVaiTro(Id) {

        toggleButtonContainerLoading(Id);
        showNotificationWithConfirm("",
            () => {
                $.ajax({
                    url: '/VaiTro/Delete/' + Id,
                    method: 'GET',
                    dataType: 'json',
                    success: function (data) {
                        toggleButtonContainerLoading(Id);
                        showNotification("warrning", "Xóa thành công")
                        $('#search-btn').click();
                    },
                    error: function (xhr, status, error) {
                        console.log(error)
                        showNotification("danger", 'Đã có lỗi xảy ra:' + xhr?.responseJSON?.ex_message);
                        toggleButtonContainerLoading(Id);
                    }
                });
            }, () => {
                toggleButtonContainerLoading(Id);
            }
        )

    };
    $(document).ready(function () {


        var dataGridInstance = $('#data-source-4').registerGrid({
            "columns": [
                {
                    "data": 'STT',
                    "title": "STT",
                    "render": function (data, type, row, meta) {
                        return Index = meta.row + meta.settings._iDisplayStart + 1;
                    },
                    "orderable": false,
                    "visible": true,
                    "width": "50px"
                },
                {
                    "data": 'TenVaiTro',
                    "title": "Tên Vai Trò",
                    "render": function (data, type, row) {
                       
                        return `<a onclick='xemVaiTro(${row.Id})'>${row.TenVaiTro}</a>`;
                    },
                    "orderable": true,
                    "visible": true
                },
                {
                    "data": 'MoTa',
                    "title": "Mô Tả",
                    "render": function (data, type, row) {
                        return data;
                    },
                    "orderable": true,
                    "visible": true
                },
                {
                    "data": 'ModerationStatusTxt',
                    "title": "Trạng thái kiểm duyệt",
                    "render": function (data, type, row) {
                        return `<td> <span class="badge rounded-pill ${getModerationStatusClass(row.ModerationStatus)}">${data}</span></td`;
                    },
                    "orderable": true,
                },

                {
                    "data": '',
                    "title": "Chức năng",
                    "render": function (data, type, row) {
                        var html = `<div class='button-container-in-grid button-container-${row.Id}'>`;
                        html += `<a href='#' title="Phân quyền " onclick='phanQuyen(${row.Id})'><i class="fa fa-plus" aria-hidden="true"></i></a>`
                        html += `<a href='#' title="Sửa " data-permission="000003002" onclick='suaVaiTro(${row.Id})'><i class="fa fa-pencil" aria-hidden="true"></i></a>`
                        if (row.ModerationStatus != 0)
                            html += `<a href='#' title="Duyệt " data-permission="000003004" onclick='duyetVaiTro(${row.Id})'><i class="fa fa-check" aria-hidden="true"></i></a>`
                        else
                            html += ` <a href='#' title="Hủy duyệt" data-permission="000003004" onclick='huyDuyetVaiTro(${row.Id})'><i class="fa fa-times" aria-hidden="true"></i></a>`

                        html += ` <a href='#' title="Xóa" data-permission="000003003" onclick='xoaVaiTro(${row.Id})'><i class="fa fa-trash-o" aria-hidden="true"></i></a>`
                        checkPermissions();
                        return html += "</div>";
                    },
                    "orderable": false,
                    "width": "150px"
                }

            ],
            length: 20,
            endpoint: "/VaiTro/GetPaged",
            prepareRequest: function (d) {
                d.SearchIn = ["TenVaiTro"];
                d.Keyword = $('#search-input').val();
                var t_gridRequest = {
                    "skip": d.start,
                    "page": (d.start / d.length) + 1,
                    "pageSize": d.length
                };
                d.t_gridRequest = JSON.stringify(t_gridRequest);
                return d;
            },

            // dataBound: function () {
            //     // $('.dataTables_processing').hide();
            //     // console.log("load xong dữ liệu")
            // },

        });
        $('#search-btn').registerButton({
            type: 'primary',
            icon: "fa fa-search",
            clickHandler: function () {
                return new Promise(function (resolve) {
                    var grid = dataGridInstance;
                    grid.page(0);//chuyển về trang đầu
                    grid.ajax.reload(null, false);
                    resolve();//cờ xác định kết thúc
                });
            }
        });
        $('#exportExcel').registerButton({
            type: 'info',
            icon: "fa fa-file-excel-o",
            clickHandler: function () {
                var grid = dataGridInstance;
                return new Promise(function (resolve, reject) {
                    $.post("/VaiTro/ExportDataToExcel", {
                        "SearchIn": ["TenVaiTro"],
                        "Keyword": $('#search-input').val()
                    })
                        .done(function (data) {
                            ChuyenHuong("external", `/Files/ExportExcel?file=${data}`, "new_tab")
                            resolve(); // Kết thúc promise
                        })
                        .fail(function (xhr, status, error) {
                            showNotification("danger", 'Đã có lỗi xảy ra:', error);
                            reject(error); // Kết thúc promise với lỗi
                        });
                });

            }
        });

        $("#search-input").enterKey(function () {
            var button = $('#search-btn');
            if (!button.hasClass("loading"))
                $('#search-btn').click();
        });

        $('#datetime-local').datepicker({
            language: 'vi',

        })
        $('#myButton').registerButton({
            type: 'primary',
            icon: "fa fa-plus",
            clickHandler: function () {
                return new Promise(function (resolve) {
                    ChuyenHuong("external", "/VaiTro/Edit/" + 0)
                    resolve();//cờ xác định kết thúc
                });
            }
        });

    });
</script>

CMS/Views/VaiTro/Phanquyen.cshtml
@model Domain.Entities.VaiTro_Entity

<div class="container-fluid d-flex row">
    <input asp-for="Id" type="hidden" />
    <div class="card-body col-6">
        <h1>
            Chức năng

            <a href="#" class="me-1 mt-1 " id="selectAllMenu" title="Tích tất cả"><i class="fa fa-check" aria-hidden="true"></i></a><span class="fw-normal">|</span>
            <a href="#" class="me-1 mt-1" id="deselectAllMenu" title="Bỏ tích tất cả"><i class="fa fa-circle-thin" aria-hidden="true"></i></a><span class="fw-normal">|</span>
            <a href="#" class="me-1 mt-1" id="closeAllMenu" title="Đóng tất cả"><i class="fa fa-times" aria-hidden="true"></i></a>


        </h1>
        <div id="containerMenu" class="tree-container"></div>
        
    </div>
    <div class="card-body col-6">
        <h1 class="mb-2">
            Quyền
            <a href="#" class="me-1" id="selectAllQuyen"><i class="fa fa-check" aria-hidden="true"></i></a><span class="fw-normal">|</span>
            <a href="#" class="me-1" id="deselectAllQuyen"><i class="fa fa-circle-thin" aria-hidden="true"></i></a><span class="fw-normal">|</span>

        </h1>
        <div id="containerQuyen" class="tree-container"></div>
    </div>
@*     <div class="card-body d-flex justify-content-end">
        <button id="saveButton">Lưu</button>
    </div> *@
    
</div>

<script>

    $(document).ready(function () {
        $('.modal-footer').html('<button type="button" id="saveButton" class="btn btn-secondary" data-bs-dismiss="modal">Lưu</button>');
        var listIdMenu = [];
        var listIdQuyen = [];
        
        
        
        var treeMenu,treeQuyen;

        
            $.ajax({
                url: '/VaiTro/GetVaiTroMenuByVaiTroId/' + $('#Id').val(),
                method: 'GET',
                dataType: 'json',
                success: function (data) {
                    
                    // console.log(data.data.map(item => item.MenuQuanTriId.toString()))
                    var list = data.data.map(item => item.MenuQuanTriId.toString());
                     treeMenu = $("#containerMenu").registerTreeView({
                        selectMode: 'checkbox',
                        values: list,
                        disables: [],
                        beforeLoad: null,
                        loaded: null,
                        url: "/MenuQuanTri/GetMenuItems",
                        onChange: function () {
                            listIdMenu = this.selectedNodes.map(item => parseInt(item.id));
                            
                            // console.log(this.values);
                            // // console.log(this.selectedNodes);
                            // // console.log(this.CurrentSelected);
                        },
                        method: 'GET',
                        closeDepth: 3
                    });
                }
            });

        
        
            $.ajax({
                url: '/VaiTro/GetVaiTroQuyenByVaiTroId/' + $('#Id').val(),
                method: 'GET',
                dataType: 'json',
                success: function (data) {
                    // console.log(data.data.map(item => item.QuyenSuDungId.toString()))
                        treeQuyen = $("#containerQuyen").registerTreeView({
                        selectMode: 'checkbox',
                        values: data.data.map(item => item.QuyenSuDungId.toString()),
                        disables: [],
                        beforeLoad: null,
                        loaded: null,
                        url: "/QuyenSuDung/GetQuyenItems",
                        onChange: function () {
                            listIdQuyen = this.selectedNodes.map(item => parseInt(item.id));
                            
                            // console.log(listIdQuyen);
                            // // console.log(this.values);
                            // console.log(this.selectedNodes);
                            // // console.log(this.CurrentSelected);
                        },
                        method: 'GET',
                        closeDepth: 1
                    });
                }
            });
        
        $("#closeAllQuyen").bind("click", function () {
            treeQuyen.collapseAll();
        })

        $("#deselectAllQuyen").bind("click", function () {
            treeQuyen.setValues([]);
        })

        $("#selectAllQuyen").bind("click", function () {
            console.log(@Html.Raw(Json.Serialize(ViewBag.AllMenuIds)));
            treeQuyen.setValues(@Html.Raw(Json.Serialize(ViewBag.AllQuyenCha)))
        })

        $("#closeAllMenu").bind("click", function () {
            treeMenu.collapseAll();
        })

        $("#deselectAllMenu").bind("click", function () {
            treeMenu.setValues([]);
        })
        
        $("#selectAllMenu").bind("click", function () {
            console.log(@Html.Raw(Json.Serialize(ViewBag.AllMenuIds)));
            treeMenu.setValues(@Html.Raw(Json.Serialize(ViewBag.AllMenuIds)))
        })


        $('#saveButton').registerButton({
            type: 'primary',
            icon: "fa fa-save",
            clickHandler: function () {
                return new Promise(function (resolve) {
                    $.ajax({
                        url: '/VaiTro/SavePhanQuyen',
                        method: 'POST',
                        contentType: 'application/json',
                        data: JSON.stringify({ IdVaiTro: parseInt($('#Id').val()), ListIdMenu: listIdMenu, ListIdQuyen: listIdQuyen }),
                        success: function (data) {
                            // console.log(data)
                            showNotification("success", data.ex_message)
                        },
                        error: function (xhr, status, error) {
                            showNotification("danger", 'Đã có lỗi xảy ra:', error);
                        }
                    });
                    resolve();//cờ xác định kết thúc
                });
            }
        });



    })
</script>

CMS/Views/VaiTro/View.cshtml
@model Domain.Entities.VaiTro_Entity


<div class="table-responsive invoice-table custom-scrollbar" id="table">
    <table class="table table-bordered table-striped">
        <tbody>
            <tr>
                <td class="item">
                    <h6 class="p-2 mb-0">Trường giá trị</h6>
                </td>
                <td class="Hours">
                    <h6 class="p-2 mb-0">Nội dung</h6>
                </td>

            </tr>
            <tr>
                <td>
                    <label>Tên vai trò</label>
                </td>
                <td>
                    <p class="itemtext">@Model.TenVaiTro</p>
                </td>

            </tr>

            <tr>
                <td>
                    <label>Mô Tả</label>
                </td>
                <td>
                    <p class="itemtext">@Model.MoTa</p>
                </td>

            </tr>









            <tr>
                <td>
                    <label>Thời gian tạo</label>
                </td>
                <td>
                    <p class="itemtext">@Model.ThoiGianTao</p>
                </td>

            </tr>
            <tr>
                <td>
                    <label>Thời gian sửa cuối</label>
                </td>
                <td>
                    <p class="itemtext">@Model.ThoiGiaSuaCuoi</p>
                </td>

            </tr>

            @if (!string.IsNullOrEmpty(Model.CreatedByText))
            {
                <tr>
                    <td>
                        <label>Người tạo</label>
                    </td>
                    <td>
                        <p class="itemtext">@Model.CreatedByText</p>
                    </td>

                </tr>
            }
            @if (!string.IsNullOrEmpty(Model.LastModifiedByText))
            {
                <tr>
                    <td>
                        <label>Người sửa cuối</label>
                    </td>
                    <td>
                        <p class="itemtext">@Model.LastModifiedByText</p>
                    </td>

                </tr>
            }



        </tbody>
    </table>
</div>