CMS/Controllers/NguoiDungController.cs
using Application.Interfaces;
using Domain.Models;
using Domain.Querys;
using Domain.Querys.Base;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using CMS.Models;
using Domain.Entities;

namespace CMS.Controllers
{
    [Authorize]
    public class NguoiDungController : BaseController
    {
        private readonly INguoiDungService _NguoiDungService;
        private readonly IMenuQuanTriService _MenuQuanTriService;
        private readonly IQuyenSuDungService _QuyenSuDungService;
        public NguoiDungController(INguoiDungService NguoiDungService, IMenuQuanTriService menuQuanTriService, IQuyenSuDungService quyenSuDungService) : base(NguoiDungService)
        {
            _NguoiDungService = NguoiDungService;
            _MenuQuanTriService = menuQuanTriService;
            _QuyenSuDungService = quyenSuDungService;
        }
        [Authorize]
        public IActionResult Index()
        {
            ViewBag.isQuanTriHT = GetCurrentUser().isQuanTriHT;
            return View();
        }
        public IActionResult PhanVaiTro(int Id)
        {

            NguoiDung_Entity oNguoiDung = new NguoiDung_Entity();
            if (Id != 0)
            {
                oNguoiDung = _NguoiDungService.GetEntity(Id);
                if (oNguoiDung == null) { oNguoiDung = new NguoiDung_Entity(); }
            }
            var allMenuIds = _MenuQuanTriService.GetAllMenuQuanTriIds();
            ViewBag.AllMenuIds = allMenuIds;
            var allMenuChaQuyen = _QuyenSuDungService.GetAllQuyenCha();
            ViewBag.AllQuyenCha = allMenuChaQuyen;
            return PartialView(oNguoiDung);
        }
        public IActionResult GetVaiTroNguoiDungByNguoiDungId(int Id)
        {
            var responeActionResult = _NguoiDungService.GetVaiTroNguoiDungByNguoiDungId(Id);
            return Ok(responeActionResult);
        }
        [HttpPost]
        public IActionResult SavePhanVaiTro([FromBody] PhanVaiTroRequest request)
        {
            request.CurrentUserId = GetCurrentUser().Id;
            var responeActionResult = _NguoiDungService.SavePhanVaiTro(request);
            return Ok(responeActionResult);
        }










        public IActionResult Edit(int Id)
        {
            NguoiDung_Entity itemEdit = new NguoiDung_Entity();
            if (Id != 0)
                itemEdit = _NguoiDungService.GetEntity(Id);
            return View(itemEdit);
        }
        public IActionResult View(int Id)
        {
            NguoiDung_Entity itemEdit = _NguoiDungService.GetEntity(Id);
            return PartialView(itemEdit);
        }

        public IActionResult Update(NguoiDung oItem)
        {
            try
            {
                var responeActionResult = _NguoiDungService.Update(oItem);
                return Ok(responeActionResult);
            }
            catch (Exception ex)
            {
                //Log.Error(ex, "Lỗi khi sửa");
                return StatusCode(500, "Đã có lỗi xảy ra. Vui lòng thử lại sau.");
            }


        }
        public IActionResult Approved(int ID)
        {
            try
            {
                var responeActionResult =  _NguoiDungService.ApprovedItem(ID);
                return Ok(responeActionResult);
            }
            catch (Exception ex)
            {
                //Log.Error("Lỗi ở /TaiLieuThucTap/Approved", ex);
                return StatusCode(500, "Đã có lỗi xảy ra. Vui lòng thử lại sau.");
            }
        }

        public IActionResult Disapproval(int ID)
        {
            try
            {
                var responeActionResult = _NguoiDungService.DisapprovedItem(ID);
                return Ok(responeActionResult);
            }
            catch (Exception ex)
            {
                //Log.Error("Lỗi ở /TaiLieuThucTap/Disapproval", ex);
                return StatusCode(500, "Đã có lỗi xảy ra. Vui lòng thử lại sau.");
            }


        }
        public IActionResult Delete(int Id)
        {
            try
            {
                var responeActionResult = _NguoiDungService.Delete(Id);
                return Ok(responeActionResult);
            }
            catch (Exception ex)
            {
                //Log.Error("Lỗi ở /TaiLieuThucTap/Delete", ex);
                return StatusCode(500, "Đã có lỗi xảy ra. Vui lòng thử lại sau.");
            }


        }
        public IActionResult Insert(NguoiDung oItem)
        {
            try
            {
                var responeActionResult = _NguoiDungService.Insert(oItem);
                return Ok(responeActionResult);

            }
            catch (Exception ex)
            {
                //Log.Error(ex, "Lỗi khi sửa");
                return StatusCode(500, "Đã có lỗi xảy ra. Vui lòng thử lại sau.");
            }


        }

        public IActionResult GetPaged(NguoiDungQuery c_query)
        {

            try
            {
                var responeActionResult = _NguoiDungService.GetPaged(c_query);
                return Ok(responeActionResult);
            }
            catch (Exception ex)
            {
                //Log.Error(ex, "Lỗi khi lấy danh sách");
                return StatusCode(500, "Đã có lỗi xảy ra. Vui lòng thử lại sau.");
            }
        }
    }
}

CMS/Views/NguoiDung/Edit.cshtml
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model Domain.Entities.NguoiDung_Entity


<script>
    function convertToDateTimeLocal(datetimeStr) {
        var dateParts = datetimeStr.split('/');
        var year = dateParts[2];
        var month = dateParts[1];
        var day = dateParts[0];
        //return `${year}-${month}-${day}T${00}:${00}`;
        return `${month}/${day}/${year}`;
    }
    $(document).ready(function () {
        $('#save').registerButton({
            type: 'primary',
            icon: "fa fa-plus",
            clickHandler: function () {
                return new Promise(function (resolve) {
                    var form = $("form.needs-validation")[0];
                    if (!form.checkValidity()) {
                        resolve();//Đặt cờ thành công
                        event.preventDefault();
                        event.stopPropagation();
                    } else {
                        event.preventDefault();
                        event.stopPropagation();
                        // let NgayChay = $("#NgayChay").val().trim();
                        // if (NgayChay && !/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/.test(NgayChay)) {
                        //     $("#NgayChay").val(convertToDateTimeLocal(NgayChay));
                        // }

                        var data = new FormData(form);
                        var xhr = new XMLHttpRequest();
                        xhr.open(form.method, form.action, true);
                        xhr.onload = function () {
                            resolve();//Đặt cờ thành công
                            if (xhr.status === 200) {
                                //$("#NgayChay").val(NgayChay);
                                showNotification("success", "Thao tác thành công!");
                                ChuyenHuong("backWithReloadGrid", null, null, "data-source-4");
                            } else {
                                //$("#NgayChay").val(NgayChay);
                                showNotification("warning", "Thao tác thất bại: " + JSON.parse(xhr?.response).ex_message)
                            }
                        };
                        xhr.send(data);

                    };
                    form.classList.add('was-validated');


                });
            }
        });
        // $('#Ngay').datepicker({
        //     language: 'vi',
        //     defaultDate: new Date(),
        //     autoClose: true
        // });
        // var initialSelection = [];
        // $("#DiaDiemDoId").registerSelect({
        //     url: '/DiaDiemDo/GetPaged',
        //     placeholder: "Chọn địa điểm đổ",
        //     queryData: {
        //     },
        //     dropdownParent: "#dropdownParent",
        //     initialSelection: initialSelection,
        //     prepareDataRequest: function (params) {
        //         return {
        //             Keyword: params.term,
        //             SearchIn: ["TenDiaDiem"],
        //         };
        //     },
        //     dataProcess: function (data) {
        //         const results = data.data
        //             .sort((a, b) => a.TenDiaDiem.localeCompare(b.TenDiaDiem))
        //             .map(item => ({
        //                 id: item.Id,
        //                 text: item.TenDiaDiem
        //             }));

        //         return { results };
        //     },
        // });
        var initialSelection = [];
        $("#CotId").registerSelect({
            url: '/Cot/GetPaged',
            placeholder: "Chọn người chạy",
            queryData: {
            },
            dropdownParent: "#dropdownParent",
            initialSelection: initialSelection,
            prepareDataRequest: function (params) {
                return {
                    Keyword: params.term,
                    SearchIn: ["TenNguoiDung"],
                };
            },
            dataProcess: function (data) {
                const results = data.data
                    .sort((a, b) => a.TenNguoiDung.localeCompare(b.TenNguoiDung))
                    .map(item => ({
                        id: item.Id,
                        text: item.TenNguoiDung
                    }));

                return { results };
            },
        });

    });
</script>

<div class="container-fluid">
    <div class="page-title">
        <div class="row">
            <div class="col-6">
                <h4>
                    @if (Model.Id > 0)
                    {
                        <text>Sửa {chức năng}</text>
                    }
                    else
                    {
                        <text>Thêm mới {chức năng}</text>
                    }
                </h4>
            </div>
            <div class="col-6">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="index.html">
                            <svg class="stroke-icon">
                                <use href="../assets/svg/icon-sprite.svg#stroke-home"></use>
                            </svg>
                        </a>
                    </li>
                    <li class="breadcrumb-item">{menu bố}</li>
                    <li class="breadcrumb-item">{Chức năng}</li>
                    <li class="breadcrumb-item active">
                        @if (Model.Id > 0)
                        {
                            <text>Sửa</text>
                        }
                        else
                        {
                            <text>Thêm mới</text>
                        }
                    </li>
                </ol>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <form asp-action="@(Model.Id == 0 ? "Insert" : "Update")" asp-controller="NguoiDung" method="post" class="card needs-validation">
                <div class="card-header">
                    <h4>Thông tin bản ghi</h4>
                </div>
                <div class="card-body custom-input">
                    <div class="row">
                        @if (Model.Id > 0)
                        {
                            <input asp-for="Id" type="hidden" />
                        }
                        
                
                    <div class="col-md-6">
                        <div class="mb-3">
                            <label asp-for="TenNguoiDung" class="form-label">TenNguoiDung</label>
                            <input asp-for="TenNguoiDung" class="form-control " placeholder="TenNguoiDung" required />
                            <span asp-validation-for="TenNguoiDung" class="text-danger"></span>
                        </div>
                    </div>
                
                
                    <div class="col-md-6">
                        <div class="mb-3">
                            <label asp-for="TenDangNhap" class="form-label">TenDangNhap</label>
                            <input asp-for="TenDangNhap" class="form-control " placeholder="TenDangNhap" required />
                            <span asp-validation-for="TenDangNhap" class="text-danger"></span>
                        </div>
                    </div>
                
                
                    <div class="col-md-6">
                        <div class="mb-3">
                            <label asp-for="Email" class="form-label">Email</label>
                            <input asp-for="Email" class="form-control " placeholder="Email" required />
                            <span asp-validation-for="Email" class="text-danger"></span>
                        </div>
                    </div>
                
                
                    <div class="col-md-6">
                        <div class="mb-3">
                            <label asp-for="MatKhau" class="form-label">MatKhau</label>
                            <input asp-for="MatKhau" class="form-control " placeholder="MatKhau" required />
                            <span asp-validation-for="MatKhau" class="text-danger"></span>
                        </div>
                    </div>
                
                
                    <div class="col-md-6">
                        <div class="mb-3">
                            <label asp-for="DienThoai" class="form-label">DienThoai</label>
                            <input asp-for="DienThoai" class="form-control " placeholder="DienThoai" required />
                            <span asp-validation-for="DienThoai" class="text-danger"></span>
                        </div>
                    </div>
                
                
                    <div class="col-md-6">
                        <div class="mb-3">
                            <label asp-for="Idp" class="form-label">Idp</label>
                            <input asp-for="Idp" class="form-control " placeholder="Idp" required />
                            <span asp-validation-for="Idp" class="text-danger"></span>
                        </div>
                    </div>
                
                
                    <div class="col-md-6">
                        <div class="mb-3">
                            <label asp-for="NgaySinh" class="form-label">NgaySinh</label>
                            <input asp-for="NgaySinh" class="form-control " placeholder="NgaySinh" required />
                            <span asp-validation-for="NgaySinh" class="text-danger"></span>
                        </div>
                    </div>
                
                
                    <div class="col-md-6">
                        <div class="mb-3">
                            <label asp-for="DiaChi" class="form-label">DiaChi</label>
                            <input asp-for="DiaChi" class="form-control " placeholder="DiaChi" required />
                            <span asp-validation-for="DiaChi" class="text-danger"></span>
                        </div>
                    </div>
                
                
                    <div class="col-md-6">
                        <div class="mb-3">
                            <label asp-for="AnhDaiDien" class="form-label">AnhDaiDien</label>
                            <input asp-for="AnhDaiDien" class="form-control " placeholder="AnhDaiDien" required />
                            <span asp-validation-for="AnhDaiDien" class="text-danger"></span>
                        </div>
                    </div>
                
                
                    <div class="col-md-6">
                        <div class="mb-3">
                            <label asp-for="TokenJira" class="form-label">TokenJira</label>
                            <input asp-for="TokenJira" class="form-control " placeholder="TokenJira" required />
                            <span asp-validation-for="TokenJira" class="text-danger"></span>
                        </div>
                    </div>
                
                
                    <div class="col-md-6">
                        <div class="mb-3">
                            <label asp-for="TinhTrangDocThan" class="form-label">TinhTrangDocThan</label>
                            <input asp-for="TinhTrangDocThan" class="form-control " placeholder="TinhTrangDocThan" required />
                            <span asp-validation-for="TinhTrangDocThan" class="text-danger"></span>
                        </div>
                    </div>
                
                
                    <div class="col-md-6">
                        <div class="mb-3">
                            <label asp-for="VaiTroNguoiDungs" class="form-label">VaiTroNguoiDungs</label>
                            <input asp-for="VaiTroNguoiDungs" class="form-control " placeholder="VaiTroNguoiDungs" required />
                            <span asp-validation-for="VaiTroNguoiDungs" class="text-danger"></span>
                        </div>
                    </div>
                
                
                    <div class="col-md-6">
                        <div class="mb-3">
                            <label asp-for="PhanQuyenNguoiDung" class="form-label">PhanQuyenNguoiDung</label>
                            <input asp-for="PhanQuyenNguoiDung" class="form-control " placeholder="PhanQuyenNguoiDung" required />
                            <span asp-validation-for="PhanQuyenNguoiDung" class="text-danger"></span>
                        </div>
                    </div>
                
                
                    <div class="col-md-6">
                        <div class="mb-3">
                            <label asp-for="MenuNguoiDung" class="form-label">MenuNguoiDung</label>
                            <input asp-for="MenuNguoiDung" class="form-control " placeholder="MenuNguoiDung" required />
                            <span asp-validation-for="MenuNguoiDung" class="text-danger"></span>
                        </div>
                    </div>
                
                        @* <div class="col-md-6 nc">
                            <div class="mb-3">
                                <label asp-for="CotId" class="form-label ">Chọn cột cần lọc</label>
                                <select asp-for="CotId" class="form-control " placeholder="cột cần lọc"></select>
                                <span asp-validation-for="CotId" class="text-danger"></span>
                            </div>
                        </div> *@

                        <div class="col-md-12 text-end">
                            <button id="save" type="button">Lưu</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

CMS/Views/NguoiDung/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">
    <div class="page-title">
        <div class="row">
            <div class="col-6">
                <h4>Danh sách người dùng</h4>
            </div>
            <div class="col-6">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="index.html">
                            <svg class="stroke-icon">
                                <use href="/svg/icon-sprite.svg#stroke-home"></use>
                            </svg>
                        </a>
                    </li>
                    <li class="breadcrumb-item">Chức năng hệ thống</li>
                    <li class="breadcrumb-item active">Người dùng</li>
                </ol>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row">

        <!-- Server-side processing Starts-->
        <div class="col-sm-12">

            <div class="card">
                <div class="card-header pb-0 card-no-border">
                    <div class="row">
                        <div class="col-md-8">
                            <div class="row">
                                <div class="col-md-6 d-flex" data-permission="000001006">
                                    <input type="text" class="form-control flex-grow-1 me-2" id="search-input" placeholder="Nhập vào từ khóa ..." autocomplete="none">
                                    <button class="btn btn-primary" id="search-btn">Tìm kiếm</button>
                                </div>

                            </div>
                        </div>
                        <div class="col-md-4 text-end">
                            <button id="exportExcel" type="button" data-permission="000001005">Xuất excel</button>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <div class="table-responsive custom-scrollbar">
                        <table class="display" id="data-source-4" style="width:100%">
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

<script>
    var isQuanTriHT = @(@ViewBag.isQuanTriHT.ToString().ToLower());

    function xemNguoiDung(Id) {
        openModalWithApi("/NguoiDung/View/" + Id, "lg");
    };
    function suaNguoiDung(Id) {
        ChuyenHuong("external", "/NguoiDung/Edit/" + Id);
    };
    function duyetNguoiDung(Id) {
        toggleButtonContainerLoading(Id);
        $.ajax({
            url: '/NguoiDung/Approve/' + Id,
            method: 'GET',
            dataType: 'json',
            success: function (data) {
                showNotification("success", "Duyệt thành công");
                toggleButtonContainerLoading(Id);
                $('#search-btn').click();
            },
            error: function (xhr, status, error) {
                showNotification("danger", 'Đã có lỗi xảy ra:', error);
                toggleButtonContainerLoading(Id);
            }
        });
    };
    function huyDuyetNguoiDung(Id) {
        toggleButtonContainerLoading(Id);
        $.ajax({
            url: '/NguoiDung/Rejected/' + Id,
            method: 'GET',
            dataType: 'json',
            success: function (data) {
                toggleButtonContainerLoading(Id);
                showNotification("success", "Hủy duyệt thành công")

                $('#search-btn').click();
            },
            error: function (xhr, status, error) {
                toggleButtonContainerLoading(Id);
                showNotification("danger", 'Đã có lỗi xảy ra:', error);
            }
        });
    };
    function xoaNguoiDung(Id) {

        toggleButtonContainerLoading(Id);
        showNotificationWithConfirm("",
            () => {
                $.ajax({
                    url: '/NguoiDung/Delete/' + Id,
                    method: 'GET',
                    dataType: 'json',
                    success: function (data) {
                        toggleButtonContainerLoading(Id);
                        showNotification("warning", "Xóa thành công")
                        $('#search-btn').click();
                    },
                    error: function (xhr, status, error) {
                        console.log(error)
                        showNotification("danger", 'Đã có lỗi xảy ra:' + xhr?.responseJSON?.ex_message);
                        toggleButtonContainerLoading(Id);
                    }
                });
            }, () => {
                toggleButtonContainerLoading(Id);

            }
        )

    };
    function xoaNguoiDungByQuanTri(Id) {

        toggleButtonContainerLoading(Id);
        showNotificationWithConfirm("",
            () => {
                $.ajax({
                    url: '/NguoiDung/DeleteNguoiDungByQuanTri/' + Id,
                    method: 'GET',
                    dataType: 'json',
                    success: function (data) {
                        toggleButtonContainerLoading(Id);
                        showNotification("warning", "Xóa thành công")
                        $('#search-btn').click();
                    },
                    error: function (xhr, status, error) {
                        console.log(error)
                        showNotification("danger", 'Đã có lỗi xảy ra:' + xhr?.responseJSON?.ex_message);
                        toggleButtonContainerLoading(Id);
                    }
                });
            }, () => {
                toggleButtonContainerLoading(Id);

            }
        )

    };
    function phanVaiTro(Id) {
        openModalWithApi("/NguoiDung/PhanVaiTro/" + Id, "xl");
    }
    $(document).ready(function () {


        var dataGridInstance = $('#data-source-4').registerGrid({
            "columns": [
                {
                    "data": 'STT',
                    "title": "STT",
                    "render": function (data, type, row, meta) {
                        return Index = meta.row + meta.settings._iDisplayStart + 1;
                    },
                    "orderable": false,
                    "visible": true,
                    "width": "50px"
                },
                {
                    "data": 'TenNguoiDung',
                    "title": "Họ và tên",
                    "render": function (data, type, row) {
                        console.log(data)
                        console.table(row)
                        return `<a onclick='xemNguoiDung(${row.Id})'>${row.TenNguoiDung}</a>`;
                    },
                    "orderable": true,
                    "visible": true
                },
                {
                    "data": 'TenDangNhap',
                    "title": "Tên đăng nhập",
                    "render": function (data, type, row) {
                        return data;
                    },
                    "orderable": true,
                    "visible": true
                },
                {
                    "data": 'Email',
                    "title": "Email",
                    "render": function (data, type, row) {
                        return data;
                    },
                    "orderable": true,
                    "visible": true
                },
                {
                    "data": 'ModerationStatus',
                    "title": "Trạng thái kiểm duyệt",
                    "render": function (data, type, row) {
                        var trangThai = "Bị khóa";
                        if (data == 0) {
                            trangThai = "Hoạt động";
                        }

                        return `<td> <span class="badge rounded-pill ${getModerationStatusClass(row.ModerationStatus)}">${trangThai}</span></td`;
                    },
                    "orderable": true,
                },

                {
                    "data": '',
                    "title": "Chức năng",
                    "render": function (data, type, row) {
                        console.log(row.ModerationStatus)
                        var html = `<div class='button-container-in-grid button-container-${row.Id}'>`;
                        html += `<a href='#' title="Phân quyền " onclick='phanVaiTro(${row.Id})'><i class="fa fa-plus" aria-hidden="true"></i></a>`
                        html += `<a href='#' title="Sửa " data-permission="000001002" onclick='suaNguoiDung(${row.Id})'><i class="fa fa-pencil" aria-hidden="true"></i></a>`
                        if (row.ModerationStatus != 0)
                            html += `<a href='#' title="Duyệt " data-permission="000001004" onclick='duyetNguoiDung(${row.Id})'><i class="fa fa-check" aria-hidden="true"></i></a>`
                        else
                            html += ` <a href='#' title="Hủy duyệt" data-permission="000001004" onclick='huyDuyetNguoiDung(${row.Id})'><i class="fa fa-times" aria-hidden="true"></i></a>`

                        html += ` <a href='#' title="Xóa" data-permission="000001003" onclick='xoaNguoiDung(${row.Id})'><i class="fa fa-trash-o" aria-hidden="true"></i></a>`
                        if (isQuanTriHT) html += ` <a href='#' title="Xóa người dùng" data-permission="000001003" onclick='xoaNguoiDungByQuanTri(${row.Id})'><i class="fa fa fa-eraser" aria-hidden="true"></i></a>`
                        return html += "</div>";
                    },
                    "orderable": false,
                    "width": "150px"
                }

            ],
            length: 20,
            endpoint: "/NguoiDung/GetPaged",
            prepareRequest: function (d) {
                d.SearchIn = ["TenNguoiDung", "TenDangNhap", "Email"];
                d.Keyword = $('#search-input').val();
                var t_gridRequest = {
                    "skip": d.start,
                    "page": (d.start / d.length) + 1,
                    "pageSize": d.length
                };
                d.t_gridRequest = JSON.stringify(t_gridRequest);
                return d;
            },

            // dataBound: function () {
            //     // $('.dataTables_processing').hide();
            //     // console.log("load xong dữ liệu")
            // },

        });
        $('#search-btn').registerButton({
            type: 'primary',
            icon: "fa fa-search",
            clickHandler: function () {
                return new Promise(function (resolve) {
                    var grid = dataGridInstance;
                    grid.page(0);//chuyển về trang đầu
                    grid.ajax.reload(null, false);
                    resolve();//cờ xác định kết thúc
                });
            }
        });
        $('#exportExcel').registerButton({
            type: 'info',
            icon: "fa fa-file-excel-o",
            clickHandler: function () {
                var grid = dataGridInstance;
                return new Promise(function (resolve, reject) {
                    $.post("/NguoiDung/ExportDataToExcel", {
                        "SearchIn": ["TenNguoiDung", "TenDangNhap", "Email"],
                        "Keyword": $('#search-input').val()
                    })
                        .done(function (data) {
                            console.log(data)
                            ChuyenHuong("external", `/Files/ExportExcel?file=${data}`, "new_tab")
                            resolve(); // Kết thúc promise
                        })
                        .fail(function (xhr, status, error) {
                            console.log(xhr);
                            showNotification("danger", 'Đã có lỗi xảy ra:', error);
                            reject(error); // Kết thúc promise với lỗi
                        });
                });

            }
        });

        $("#search-input").enterKey(function () {
            var button = $('#search-btn');
            if (!button.hasClass("loading"))
                $('#search-btn').click();
        });

        $('#datetime-local').datepicker({
            language: 'vi',

        })

        checkPermissions();
    });
</script>