CMS/Controllers/QuyenSuDungController.cs
using Application.Interfaces;
using Domain.Models;
using Domain.Querys;
using Domain.Querys.Base;
using Microsoft.AspNetCore.Mvc;
using Domain.Entities;
using System.Text;

namespace CMS.Controllers
{
    public class QuyenSuDungController : BaseController
    {
        private readonly IQuyenSuDungService _QuyenSuDungService;
        public QuyenSuDungController(INguoiDungService nguoiDungService,IQuyenSuDungService QuyenSuDungService) : base(nguoiDungService)
        {
            _QuyenSuDungService = QuyenSuDungService;
        }
        public IActionResult Index()
        {
            return View();
        }
        //[HttpGet("/permissions.js")]
        //public IActionResult GetPermissionsJs()
        //{
        //    List<string> maQuyen = _PhanQuyenNguoiDungsRepository.GetListEntityByUserId(CurrentUser.Id).Select(a => a.QuyenSuDung.MaQuyen.ToString()).ToList();
        //    List<string> allMaQuyen = _QuyenSuDungsRepository.GetAllEntity().Select(a => a.MaQuyen.ToString()).ToList();
        //    //<button id="myButton" data-permission="001">Click me</button>
        //    StringBuilder listDataMission = new StringBuilder();
        //    for (int i = 0; i < allMaQuyen.Count; i++)
        //    {
        //        if (!maQuyen.Contains(allMaQuyen[i]))
        //        {
        //            listDataMission.Append($"$('[data-permission=\"{allMaQuyen[i]}\"]').hide();");
        //            listDataMission.Append($"$('[data-permission=\"{allMaQuyen[i]}\"]').removeClass(\"d-flex\");");
        //        }
        //    }
        //    string jsContent = @"
        //        function checkPermissions() {"
        //           + listDataMission.ToString() +
        //        "}";
        //    // Trả về nội dung JavaScript với loại nội dung application/javascript
        //    return Content(jsContent, "application/javascript");
        //}
        [HttpGet("/permissions.js")]
        public IActionResult GetPermissionsJs()
        {
            //List<string> maQuyen = _PhanQuyenNguoiDungsRepository.GetListEntityByUserId(CurrentUser.Id).Select(a => a.QuyenSuDung.MaQuyen.ToString()).ToList();
            //List<string> allMaQuyen = _QuyenSuDungsRepository.GetAllEntity().Select(a => a.MaQuyen.ToString()).ToList();
            ////<button id="myButton" data-permission="001">Click me</button>
            StringBuilder listDataMission = new StringBuilder();
            //for (int i = 0; i < allMaQuyen.Count; i++)
            //{
            //    if (!maQuyen.Contains(allMaQuyen[i]))
            //    {
            //        listDataMission.Append($"$('[data-permission=\"{allMaQuyen[i]}\"]').hide();");
            //        listDataMission.Append($"$('[data-permission=\"{allMaQuyen[i]}\"]').removeClass(\"d-flex\");");
            //    }
            //}
            string jsContent = @"
                function checkPermissions() {"
                   + listDataMission.ToString() +
                "}";
            // Trả về nội dung JavaScript với loại nội dung application/javascript
            return Content(jsContent, "application/javascript");
        }




        public IActionResult AddSubItem(int Id)
        {

            QuyenSuDung_Entity itemMenu = new QuyenSuDung_Entity();
            if (Id != 0)
            {
                var itemMenuParrent = _QuyenSuDungService.GetEntity(Id);
                itemMenu.QuyenCha = itemMenuParrent;
            }
            return View("Edit", itemMenu);
        }




        public IActionResult GetQuyenItems()
        {
            return Ok(_QuyenSuDungService.GetTreeQuyenTreeView());
        }

        //public IActionResult GetQuyenIdByVaiTroId(int id)
        //{
        //    var listQuyen = _VaiTroQuyensRepository.GetByVaiTroId(id).Select(a => a.QuyenSuDungId).ToList();
        //    return Ok(listQuyen);
        //}

        public IActionResult GetQuyenIdByVaiTroIdAndNguoiDungId(int idNguoiDung, string IdVaiTroString)
        {
            List<int> result = _QuyenSuDungService.GetQuyenIdByVaiTroIdAndNguoiDungId(idNguoiDung,IdVaiTroString);
            return Ok(result);
        }













        public IActionResult Edit(int Id)
        {

            QuyenSuDung_Entity itemMenu = new QuyenSuDung_Entity();
            QuyenSuDung_Entity itemMenuCha = new QuyenSuDung_Entity();
            if (Id != 0)
            {
                itemMenu = _QuyenSuDungService.GetEntity(Id);
                if (itemMenu.QuyenSuDungCha != null)
                {
                    itemMenuCha = _QuyenSuDungService.GetEntity((int)itemMenu.QuyenSuDungCha);
                    itemMenu.QuyenCha = itemMenuCha;
                }

                if (itemMenu == null) { itemMenu = new QuyenSuDung_Entity(); }
            }

            return View(itemMenu);
        }
        public IActionResult View(int Id)
        {
            QuyenSuDung_Entity itemEdit = _QuyenSuDungService.GetEntity(Id);
            return PartialView(itemEdit);
        }

        public IActionResult Update(QuyenSuDung oItem)
        {
            try
            {
                oItem.CurrentUserId = GetCurrentUser().Id;
                var responeActionResult = _QuyenSuDungService.Update(oItem);
                return Ok(responeActionResult);
            }
            catch (Exception ex)
            {
                //Log.Error(ex, "Lỗi khi sửa");
                return StatusCode(500, "Đã có lỗi xảy ra. Vui lòng thử lại sau.");
            }


        }
        public IActionResult Approved(int ID)
        {
            try
            {
                var responeActionResult =  _QuyenSuDungService.ApprovedItem(ID);
                return Ok(responeActionResult);
            }
            catch (Exception ex)
            {
                //Log.Error("Lỗi ở /TaiLieuThucTap/Approved", ex);
                return StatusCode(500, "Đã có lỗi xảy ra. Vui lòng thử lại sau.");
            }
        }

        public IActionResult Disapproval(int ID)
        {
            try
            {
                var responeActionResult = _QuyenSuDungService.DisapprovedItem(ID);
                return Ok(responeActionResult);
            }
            catch (Exception ex)
            {
                //Log.Error("Lỗi ở /TaiLieuThucTap/Disapproval", ex);
                return StatusCode(500, "Đã có lỗi xảy ra. Vui lòng thử lại sau.");
            }


        }
        public IActionResult Delete(int Id)
        {
            try
            {
                var responeActionResult = _QuyenSuDungService.Delete(Id);
                return Ok(responeActionResult);
            }
            catch (Exception ex)
            {
                //Log.Error("Lỗi ở /TaiLieuThucTap/Delete", ex);
                return StatusCode(500, "Đã có lỗi xảy ra. Vui lòng thử lại sau.");
            }


        }
        public IActionResult Insert(QuyenSuDung oItem)
        {
            try
            {
                oItem.CurrentUserId = GetCurrentUser().Id;
                var responeActionResult = _QuyenSuDungService.Insert(oItem);
                return Ok(responeActionResult);

            }
            catch (Exception ex)
            {
                //Log.Error(ex, "Lỗi khi sửa");
                return StatusCode(500, "Đã có lỗi xảy ra. Vui lòng thử lại sau.");
            }


        }

        public IActionResult GetPaged(QuyenSuDungQuery c_query)
        {

            try
            {
                var responeActionResult = _QuyenSuDungService.GetPaged(c_query);
                return Ok(responeActionResult);
            }
            catch (Exception ex)
            {
                //Log.Error(ex, "Lỗi khi lấy danh sách");
                return StatusCode(500, "Đã có lỗi xảy ra. Vui lòng thử lại sau.");
            }
        }
    }
}

CMS/Views/QuyenSuDung/Edit.cshtml
@model Domain.Entities.QuyenSuDung_Entity

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var oQuyenCha = Model.QuyenCha;
    string oQuyenChaJson = oQuyenCha != null ? Newtonsoft.Json.JsonConvert.SerializeObject(oQuyenCha) : "{}";
}
<div class="container-fluid">
    <div class="page-title">
        <div class="row">
            <div class="col-6">
                <h4>
                    @if (Model.Id > 0)
                    {
                        <text>Sửa quyền</text>
                    }
                    else
                    {
                        <text>Thêm quyền mới</text>
                    }
                </h4>
            </div>
            <div class="col-6">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="index.html">
                            <svg class="stroke-icon">
                                <use href="../assets/svg/icon-sprite.svg#stroke-home"></use>
                            </svg>
                        </a>
                    </li>
                    <li class="breadcrumb-item"> Chức năng hệ thống</li>
                    <li class="breadcrumb-item">Quyền</li>
                    <li class="breadcrumb-item active">
                        @if (Model.Id > 0)
                        {
                            <text>Sửa</text>
                        }
                        else
                        {
                            <text>Thêm mới</text>
                        }
                    </li>
                </ol>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <form asp-action="@(Model.Id == 0 ? "Insert" : "Update")" asp-controller="QuyenSuDung" method="post" class="card needs-validation">
                <div class="card-header">
                    <h4>Thông tin bản ghi</h4>
                </div>
                <div class="card-body custom-input">
                    <div class="row">
                        @if (Model.Id > 0)
                        {
                            <input asp-for="Id" type="hidden" />
                        }
                        <div class="col-md-6">
                            <div class="mb-3">
                                <label asp-for="TenQuyen" class="form-label">Quyền</label>
                                <input asp-for="TenQuyen" class="form-control " placeholder="Quyền" required />
                                <span asp-validation-for="TenQuyen" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="mb-3">
                                <label asp-for="MaQuyen" class="form-label">Mã quyền</label>
                                <input asp-for="MaQuyen" class="form-control " placeholder="Mã quyền" required />
                                <span asp-validation-for="MoTa" class="text-danger"></span>
                            </div>
                        </div>

                        <div class="col-md-12">
                            <div class="mb-3">
                                <label asp-for="QuyenSuDungCha" class="form-label ">Quyền cha ( quyền trực thuộc)</label>
                                <select asp-for="QuyenSuDungCha" class="form-control " placeholder="Quyền cha"></select>
                                <span asp-validation-for="QuyenSuDungCha" class="text-danger"></span>

                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="mb-3">
                                <label asp-for="MoTa" class="form-label ">Mô tả</label>
                                <textarea asp-for="MoTa" class="form-control " placeholder="Mô tả"></textarea>
                                <span asp-validation-for="MoTa" class="text-danger"></span>

                            </div>
                        </div>

                        <div class="col-md-12 text-end">
                            <button id="save" type="button">Lưu</button>
                        </div>
                    </div>


                </div>


            </form>
        </div>
    </div>

</div>
<script>
    function convertToSlug(text) {
        return text.toLowerCase().replace(/ /g, '').normalize('NFD').replace(/[\u0300-\u036f]/g, "");
    }
    $(document).ready(function () {
        var oQuyenCha = @Html.Raw(oQuyenChaJson);
        var initialSelection = oQuyenCha ? [{
            text: oQuyenCha.TenQuyen,

            id: oQuyenCha.Id
        }] : [];
        $("#QuyenSuDungCha").registerSelect({
            url: '/QuyenSuDung/GetPaged',
            placeholder: "Chọn menu cha",
            queryData: {

                // bổ sung các param cần thiết vào
            },
            prepareDataRequest: function (params) {
                var parameter = {
                    keyword: params.term,
                    SearchIn: ["TenQuyen"],
                }
                return parameter;
            },
            initialSelection: initialSelection,
            dataProcess: function (data) {
                return {
                    //filter theo  item.ModerationStatus == 0 (da duyet)
                    results: data.data.filter(item => item.ModerationStatus == 0).map(function (item) {
                        return {
                            id: item.Id,
                            text: item.TenQuyen
                        };
                    })
                };
            },
        });

        $('#save').registerButton({
            type: 'primary',
            icon: "fa fa-plus",
            clickHandler: function () {
                return new Promise(function (resolve) {
                    var form = $("form.needs-validation")[0];
                    if (!form.checkValidity()) {
                        resolve();//Đặt cờ thành công
                        event.preventDefault();
                        event.stopPropagation();
                    } else {
                        event.preventDefault();
                        event.stopPropagation();
                        var data = new FormData(form);
                        var xhr = new XMLHttpRequest();
                        xhr.open(form.method, form.action, true);
                        xhr.onload = function () {
                            resolve();//Đặt cờ thành công
                            if (xhr.status === 200) {
                                console.log(xhr)
                                showNotification("success", "Thao tác thành công!");
                                ChuyenHuong("external", "/QuyenSuDung/Index")
                            } else {

                                showNotification("warning", "Thao tác thất bại!")
                            }
                        };
                        xhr.send(data);

                    };
                    form.classList.add('was-validated');


                });
            }
        });
    });

</script>

CMS/Views/QuyenSuDung/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container-fluid">
    <div class="page-title">
        <div class="row">
            <div class="col-6">
                <h4>Danh sách quyền</h4>
            </div>
            <div class="col-6">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="index.html">
                            <svg class="stroke-icon">
                                <use href="../assets/svg/icon-sprite.svg#stroke-home"></use>
                            </svg>
                        </a>
                    </li>
                    <li class="breadcrumb-item"> Chức năng hệ thống</li>
                    <li class="breadcrumb-item active">Danh sách quyền sử dụng</li>
                </ol>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-6">
                            <h4>Danh sách quyền</h4>
                            <p class="f-m-light mt-1">
                                Quản trị danh sách quyền
                            </p>
                        </div>
                        <div class="col-md-6 text-end">
                            <button id="myButton" type="button" data-permission="001001">Thêm mới</button>
                        </div>
                    </div>



                </div>
                <div class="card-body">
                    <div id="container" class="tree-container"></div>
                </div>
            </div>
        </div>

    </div>
</div>

<script>


    $(document).ready(function () {

        var treeMenu = $("#container").registerTreeView({
            selectMode: '',
            values: [],
            disables: [],
            beforeLoad: null,
            loaded: null,
            url: "/QuyenSuDung/GetQuyenItems",
            editCallback: function (ItemId) {
                ChuyenHuong("external", "/QuyenSuDung/Edit/" + ItemId)
            },
            approvedCallback: function (ItemId) {
                $.ajax({
                    url: '/QuyenSuDung/Approved/' + ItemId,
                    method: 'GET',
                    dataType: 'json',
                    success: function (data) {
                        ChuyenHuong("reload")
                    },
                    error: function (xhr, status, error) {
                        showNotification("danger", 'Đã có lỗi xảy ra:', error);
                    }
                });
            },
            peddingCallback: function (ItemId) {
                $.ajax({
                    url: '/QuyenSuDung/Disapproval/' + ItemId,
                    method: 'GET',
                    dataType: 'json',
                    success: function (data) {
                        ChuyenHuong("reload")
                    },
                    error: function (xhr, status, error) {
                        showNotification("danger", 'Đã có lỗi xảy ra:', error);
                    }
                });
            },
            addsubCallback: function (ItemId) {
                ChuyenHuong("external", "/QuyenSuDung/AddSubItem/" + ItemId)
            },
            deleteCallback: function (ItemId) {
                $.ajax({
                    url: '/QuyenSuDung/Delete/' + ItemId,
                    method: 'GET',
                    dataType: 'json',
                    success: function (data) {
                        ChuyenHuong("reload")
                    },
                    error: function (xhr, status, error) {
                        console.log()
                        showNotification("danger", 'Đã có lỗi xảy ra:' + xhr?.responseJSON?.ex_message);
                    }
                });
            },
            onChange: function () {
                // console.log(this.values);
                // console.log(this.selectedNodes);
                // console.log(this.CurrentSelected);
            },
            method: 'GET',
            closeDepth: 3
        });




        $('#myButton').registerButton({
            type: 'primary',
            icon: "fa fa-plus",
            clickHandler: function () {
                return new Promise(function (resolve) {
                    ChuyenHuong("external", "/QuyenSuDung/Edit")
                    resolve();//cờ xác định kết thúc
                });
            }
        });



    })
</script>